services:
  - type: worker
    name: nitropix
    env: python
    plan: free

    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh

    startCommand: python render_bot.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9